### ISSUE TITLE
Regarding your fork of @spicy-ui/styled-system

### ISSUE THREAD

**Issue by South-Paw** [The-Code-Monkey/The-Code-Monkey#1]
Hi there,

I'm unable to report issues on your fork so I'm doing so here

I'm aware you have a fork of [`spicy-ui/styled-system`](https://github.com/spicy-ui/styled-system) here [`The-Code-Monkey/styled-system`](https://github.com/The-Code-Monkey/styled-system) and upon comparing the fork to the main repo (to see if there were any changes or fixes you've made I should merge back into the master branch) I noticed that you have changed the copyright notice in [this commit](https://github.com/The-Code-Monkey/styled-system/commit/ed260973272a30744a8da02755c1e0cdcb666d39#diff-c693279643b8cd5d248172d9c22cb7cf4ed163a3c98c8a3f69c2717edd3eacb7).

Please note, the copyright noticed in spicy-ui states:

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

If you're unclear, this means you cannot change the copyright owner to yourself as that would not be "The above copyright notice and this permission notice" as aforementioned from the original codebase.

I'm sure you can understand that am a little upset about putting in the work of making something and then seeing someone fork it and claim it as their own and remove my name from the copyright notice. I'm sure if someone was to do the same to one of your open source repositories you would feel much the same.

If you could revert the copyright notice to the correct original one that would be appreciated and this doesn't need to discussed again.

Much appreciated,
Alex

**Comment by The-Code-Monkey** [comment]
Hey Alex,

Yeah not sure what has happened there I'll try and enable issues on that repo, and to do with the licence not sure how that was updated I will revert it

**Comment by South-Paw** [comment]
❤️ thank you really, I appreciate it!

I'm genuinely happy to see you fork the project and remix it to what you need it to be - thats what open source is all about.

On a side note; if there are any things you've fixed that I should fix in the original repo (or, that you happen to come across in the future) feel free to let me know via an issue.
